### ISSUE TITLE
报DexArchiveBuilderException错误

### ISSUE THREAD

**Issue by zhukai123** [MirkoWu/BaseLibrary#1]
您好,我新建项目导入您的baseLib,疯狂的报DexArchiveBuilderException错误,
试了好多解决方法都不行,用的是gradle:3.0.1   运行平台是:SDK:26

**Comment by MirkoWu** [comment]
因为lib里面使用了JAVA8，主项目gradle那里也要添加
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

**Comment by zhukai123** [comment]
确实是java8配置的原因,很感谢,这个库很实用

**Comment by MirkoWu** [comment]
谢谢支持，有问题可以随时issues
