### ISSUE TITLE
在查看webView之后，点击返回会报错

### ISSUE THREAD

**Issue by phpzysw** [MirkoWu/BaseLibrary#2]
webview能正常显示网页，但是按返回键退出APP会直接停止运行。
 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ProgressBar.setVisibility(int)' on a null object reference
     at com.mirkowu.baselibrarysample.ui.webView.WebViewActivity$1.onProgressChanged(WebViewActivity.java:156)

**Comment by MirkoWu** [comment]
应该是WebView在Activity销毁后回调导致的，对onProgressChanged 和onPageFinished 中尽可能做一下判空处理吧。已更新。

**Comment by MirkoWu** [comment]
可以发下你那个网址吗？

**Comment by phpzysw** [comment]
你是说浏览器输入的网址吗，就是默认的百度啊

**Comment by phpzysw** [comment]
博主你的改动我也试过，加非空判断也不行，你自己是没问题的嘛

**Comment by MirkoWu** [comment]
暂时没出现你那个问题。你再在onDestroy()中加一句 mProgress=null；应该可以的。还不行的话就把onProgressChange和onPageFinish()里面的代码注释吧。

**Comment by phpzysw** [comment]
我尝试将webview的销毁代码放在onPause()方法里，就没问题了

**Comment by MirkoWu** [comment]
@Override
    public void onDestroy() {
        if (mProgressBar != null) {
            mProgressBar = null;
        }
        if (mWebView != null) {
            mWebView.loadDataWithBaseURL(null, "", "text/html", "utf-8", null);
            mWebView.clearHistory();
            mWebView.destroy();
            mWebView = null;
        }
        super.onDestroy();
    }
这样试下

**Comment by phpzysw** [comment]
不行欸

**Comment by MirkoWu** [comment]
可以把你当前的手机品牌和android 系统发下吗？

**Comment by phpzysw** [comment]
我用的自带模拟器
![image](https://user-images.githubusercontent.com/33085000/54168063-c6613f80-44a7-11e9-9160-5091726db1e8.png)

**Comment by phpzysw** [comment]
![image](https://user-images.githubusercontent.com/33085000/54168208-5d2dfc00-44a8-11e9-87f6-1409996c3790.png)
把webview.Destroy放到前面也可以

**Comment by phpzysw** [comment]
。。。其实就是onDestroy里的super方法的位置放错了把。。。。要放方法的第一行把

**Comment by MirkoWu** [comment]
mWebView.setWebChromeClient(new WebChromeClient() {
            @Override
            public void onProgressChanged(WebView view, int newProgress) {
                if (mProgressBar != null) {
                    if (newProgress >= 99) {
                        mProgressBar.setVisibility(View.GONE);
                    } else {
                        mProgressBar.setVisibility(View.VISIBLE);
                        mProgressBar.setProgress(newProgress);
                    }
                }
            }
        });
        mWebView.setWebViewClient(new WebViewClient() {
            @Override
            public void onPageFinished(WebView view, String url) {
                super.onPageFinished(view, url);
                if (mProgressBar != null) {
                    mProgressBar.setVisibility(View.GONE);
                }
            }
        });


 @Override
    public void onDestroy() {
        if (mProgressBar != null) {
            mProgressBar = null;
        }
        if (mWebView != null) {
            mWebView.loadDataWithBaseURL(null, "", "text/html", "utf-8", null);
            mWebView.clearHistory();
            mWebView.destroy();
            mWebView = null;
        }
        super.onDestroy();
    }
复现了，这样修改就不会有问题了。

**Comment by MirkoWu** [comment]
super在**构造方法**里必须放在第一行，成员函数没限制，这是JAVA基础。

**Comment by phpzysw** [comment]
哦哦，可是为啥我就
![image](https://user-images.githubusercontent.com/33085000/54168775-22799300-44ab-11e9-90b2-b746d5afe4d9.png)这样就好了，只是把super放到前面，是不是要先解绑控件

**Comment by MirkoWu** [comment]
你这样不加判空 还是会Crash的。不是这里的问题，我比较好奇 ，你加了判空，NPE是怎么来的？是不是使用了AS的增量编译？

**Comment by phpzysw** [comment]
03-12 01:55:02.494 29244-29244/com.mirkowu.baselibrarysample A/chromium: [FATAL:jni_android.cc(249)] Check failed: false. Please include Java exception stack in crash report按你上面的代码写的。你说的NPE是最早的错误，后面加了非空，就报这个错了。
