### ISSUE TITLE
有MVVM 的例子吗

### ISSUE THREAD

**Issue by crfmoon** [MirkoWu/BaseLibrary#3]

**Comment by MirkoWu** [comment]
[databinding](https://github.com/MirkoWu/BaseLibrary/tree/master/app/src/main/java/com/mirkowu/baselibrarysample/dataBinding) 这个是根据databinding封装的base ,你看下有没有demo，LiveData 那些暂时还没加进来，后面会考虑。

**Comment by crfmoon** [comment]
好的，希望加入mvvm设计
