### ISSUE TITLE
BaseRVAdapter使用问题

### ISSUE THREAD

**Issue by Rabbit95** [MirkoWu/BaseLibrary#4]
祝国庆快乐！
请问在继承BaseRVAdapter后我的现有数据应该如何装载到Adapter?如下：
` 

public class RecyclerViewAdapter extends BaseRVAdapter<List < HomeEntityBean > > {

    public RecyclerViewAdapter(int layoutResId,List<HomeEntityBean> homeEntityBeans) {
        super(layoutResId);
    }

    @Override
    public void onBindVH(BaseRVHolder holder, List<HomeEntityBean> data, int position) {
        holder.setText(R.id.item_title,data.get(position).title);
        holder.setImageDrawable(R.id.item_icon,data.get(position).icon);
    }
}

`
我在构造函数传入了LayoutId，但是不知道怎么把现有的List < HomeEntityBean > 传入BaseRVAdapter。

**Comment by Rabbit95** [comment]
@MirkoWu

**Comment by Rabbit95** [comment]
搞定了，在BaseRVAdapter中重写BaseQuickAdapter带两个参数的构造函数，将数据传递给BaseQuickAdapter，继承BaseRVAdapter的RecyclerViewAdapter也重写这个构造函数，将数据传递给BaseRVAdapter即可！

**Comment by MirkoWu** [comment]
直接setNewData(),复写也成



---原始邮件---
发件人: "Rabbit95"<notifications@github.com&gt;
发送时间: 2019年10月5日(星期六) 下午2:51
收件人: "MirkoWu/BaseLibrary"<BaseLibrary@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"MirkoWu"<709651717@qq.com&gt;;
主题: Re: [MirkoWu/BaseLibrary] BaseRVAdapter使用问题 (#4)



搞定了，在BaseRVAdapter中重写BaseQuickAdapter带两个参数的构造函数，将数据传递给BaseQuickAdapter，继承BaseRVAdapter的RecyclerViewAdapter也重写这个构造函数，将数据传递给BaseRVAdapter即可！
